### ISSUE TITLE
is this if...

### ISSUE THREAD

**Issue by Dil3mm4** [MicroSur/sur_myevic#12]
https://github.com/MicroSur/sur_myevic/blob/64249069e8d7cca3cd6a335b7a5699356e854079/src/events.c#L410
is this if controlling the device lock? 
This is your code:

			
		 if ( dfStatus.off )
					{
						if ( FireClicksEvent != 17 )
						{
							FireClicksEvent = 0;
						}
					}
					break; 

Shouldn't be something like that?

	
				if ( dfStatus.off )
					{
						if ( FireClicksEvent != 17 )
						{
							FireClicksEvent = 0;
                                                        **ShowClock();**
						}
					}
					break;

Or the hypotetic **ShowClock();** its defined elsewhere?

I would like to know where the whole ON/OFF process gets handled (showing clock on lockscreen, behaviour on clicks and so on) 

Would you be so kind to point out the sources lines @MicroSur ?

**Comment by MicroSur** [comment]
So many places to insert )

https://github.com/MicroSur/sur_myevic/blob/64249069e8d7cca3cd6a335b7a5699356e854079/src/eh.c#L183
