### ISSUE TITLE
RU значит по-русски

### ISSUE THREAD

**Issue by MicroSur** [MicroSur/sur_myevic#13]
Диалог по данной прошивке и по-русски приветствуется )

**Comment by Dil3mm4** [comment]
Хотел бы я говорить по-русски :D

**Comment by MicroSur** [comment]
Отличия моего SME FW от оригинального myevic:
(пошёл по пути - максимум в меню мода)

- в меню: настройка действий на 5 кликов фаер.
- в меню: отключение мода по достижении установленного количества затяжек.
- в меню: вывод в инфо-линию потраченной энергии wh.
- в меню: настройка задержки показаний на экране после затяжки.
- в меню: настройка задержки показа логотипа/3D/часов.
- в меню: режим "лёгкий" варивольт. Экран WV, но без изменения выходного напряжения при затяжке.
- в меню: настройка второго контраста для экранов скрин-сейвера и зарядки.
- в меню: настройка переворота экрана при затяжке.
- в меню: коррекция температуры мода.
- в меню: редактирование своего профиля батареи.
- в меню: показ часов по клику в выключенном состоянии.
- дополнительная инфолиния-клон на экране.
- инфо-линия: показ расчетного внутреннего сопротивления батарей.
- восстановлена работа защиты при случайной затяжке, вплоть до отключения мода.
- блокировка сопротивления блокирует всегда текущее реальное.
- гашение экрана зарядки кнопкой минус.
- показ дня недели с цифровыми часами.
- дополнено поддержкой Primo v1/v2, Predator228, Primo mini.
- геометрически ровный по возможности интерфейс.
- Тетрис, дополнительные 3D заставки.

В будущем:
- в меню: установка максимальных величин мощностей, вольтажа, температуры мода.
- смена действий кнопок плюс-минус местами.

**Comment by MicroSur** [comment]
Оформился полный русский мануал по текущей версии SME
https://github.com/MicroSur/sur_myevic/blob/master/README_ru.md

**Comment by hriisd80** [comment]
Привет, можете ли вы добавить опцию power bank в меню?

**Comment by MicroSur** [comment]
Нет не могу, не умею. Я только допиливаю прошивку, Повербанк достаточно серьезная и малоперспективная опция. Например перегрев в модах на 3 батарейки удручает.
