### ISSUE TITLE
any support for Wismec Gen3? or is it my user error?

### ISSUE THREAD

**Issue by vapelifeyo** [MicroSur/sur_myevic#14]
Was wondering if anyone else has the "please confirm the hardware version!!!" or if its just me, is it supported even, if not will it be?
**Box Model:**
Wismec Rx Gen3
**Coil setup:**
N/A

**Comment by MicroSur** [comment]
I have to buy a mod to make it support. I'm not planning yet

**Comment by MicroSur** [comment]
I tried writing support of rx gen3, welcome to test with latest bin...

**Comment by vapelifeyo** [comment]
Wow you are my hero , il give it a shot tonight and ill let you know about
my results! :)

**Comment by vapelifeyo** [comment]
some problems : with detail, 
1.it now successfully installs and the ui looks great when i can see it
2. the screen is constantly flashing "too hot" or "batteries too low" (its not actually hot at all and batteries are fully charged).
3. i hear a small electric click inside the device every time it tells me my batteries are too low
4. i am able to get into the settings and the screen will not flash and i can navigate freely, i have disabled all modes other than power too see if that was the case, upon returning to the home screen it started to flash.
I could give more details if you need them.
also thank you for attempting this compatibility project i don't mean to be too pushy i just figured you'd like to know the issues for trouble shooting!

**Comment by MicroSur** [comment]
Thanks, not enough skills, sorry...

**Comment by vapelifeyo** [comment]
If you had the mod would you be able to develop it ?

**Comment by MicroSur** [comment]
Yes, I will try to support it.
Maybe I'll buy this mod too.

**Comment by MicroSur** [comment]
Can you test with latest bin pls...

**Comment by vapelifeyo** [comment]
Thanks for another attempt, I will test once I'm home from work in 8 hrs!

**Comment by vapelifeyo** [comment]
hey, no luck again same issues persist. :(

**Comment by MicroSur** [comment]
I found another my mistake...

**Comment by vapelifeyo** [comment]
No problem friend , let me know when you find a fix :)

**Comment by vapelifeyo** [comment]
hey! it works now , it still said "device too hot" but i messed around with expert setting and changed temp for F not C (im not sure if that fixed it) but after messing around with many settings its finally working :)

**Comment by MicroSur** [comment]
Good news, thank you )
Is the voltage of all the batteries and resistance of the atomizer showing correctly?

**Comment by vapelifeyo** [comment]
Yes it is! :)

**Comment by Dil3mm4** [comment]
With latest binaries the warning "battery low" popups randomly on battery full charged even on RX2/3

**Comment by MicroSur** [comment]
Dil3mm4, can U tell me more? I use rx23 every day with now problem.

**Comment by Dil3mm4** [comment]
MicroSur I don't really know what's going on, but after flashing the latest two binaries the error pops out totally randomly  in standby mode

**Comment by MicroSur** [comment]
Battery low in standby mode? I dont understand You...

**Comment by MicroSur** [comment]
May be You have video with this issue?

**Comment by Dil3mm4** [comment]
"While not firing" on screensaver mode, or with black screen, sometimes
pops out

Il gio 5 ott 2017 21:54 Alexander <notifications@github.com> ha scritto:
