### ISSUE TITLE
RX 2/3 dual battery setup

### ISSUE THREAD

**Issue by Dil3mm4** [MicroSur/sur_myevic#15]
Hello.
Noticed that on dual battery the max output is set to 9V. 
Is it safe to use it on 9V with dual battery?
According to the official firmware on dual battery the limit is set about 6V. 
On triple 9V. 

It would be good for me to use the RX on dual battery at 9V output. 
I just don't know if it's safe. 

Thank you.

**Comment by MicroSur** [comment]
This max voltage will not bite you. It can not be achieved in dual batt mode.

**Comment by Dil3mm4** [comment]
It can't be achieved? 
It would be nice if we could do that. 
Like the Evic VTC Dual.

**Comment by MicroSur** [comment]
It is impossible without hardware step-up converter.
RX2 can give you the sum of the voltages of two series-connected batteries maximum (approximately). 
And this voltage will only decrease.
