### ISSUE TITLE
RX Gen 3 stops fast charging before reaching 100%

### ISSUE THREAD

**Issue by ninjanick999** [MicroSur/sur_myevic#19]
**Box Model:**
RX Gen 3
**Coil setup:**
Smok TFV12

When charging the device at 2 amps, the unit will stop charging after 10-20 min
I'm not sure if this is an overheating issue, as the device seems to reach the temp limit point when charging.
I noticed that this limit can be changed in the settings, however I do not know if it is safe to raise (hopefully you could shed more light on that).

I lowered the max charge amps to 1.5 in the settings and I am trying to see if I can get it to charge fully with that setting

**Comment by MicroSur** [comment]
What are the temperature settings?
What temperature shows the mode in idle time?

The temperature sensor may be inaccurate.
Hot to the touch?

**Comment by ninjanick999** [comment]
I run it in power mode most of the time, with all of the stock settings.
On idle it says 29C to 35C, which now looking at it seems a little off.
It's never super hot when I get it to the overheat point, It's a bit warm but I am still able to hold the device fine.

**Comment by MicroSur** [comment]
I asked for board temperature maximum setting
[https://i.imgur.com/Ghmye6e.png](url)
and here
[https://i.imgur.com/ZD5H0Tr.png](url)

I think it Is an overheating issue...

**Comment by ninjanick999** [comment]
Oh, sorry about that.
It's set to 70 C
Is it safe to change this value or will it cause overheating issues?

**Comment by MicroSur** [comment]
What about a test with a 1.5A charge setting?
May be you have weak usb adapter...
What boart temperature shown while charging...
I need more info.

**Comment by ninjanick999** [comment]
I have tested it with different amp settings, and it seems to fully charge at 1.00 amps, but any more starts to cause it to over heat and stop. As for the temperature, it will run up to 70 if I have it set higher than 1.00 amps. At 1 amps it gets to around 64-66 ish.

**Comment by MicroSur** [comment]
How does the mod behave when charging on the official firmware?
If you feel that the mod heats up much less than the sensor shows, you can increase its maximum.

**Comment by ninjanick999** [comment]
I haven't used the stock firmware much. I flashed this right after buying it.
I'll flash back and use it a bit, and let you know how it feels.
