### ISSUE TITLE
Suggestion: Auto adjust locked resistance 

### ISSUE THREAD

**Issue by Dil3mm4** [MicroSur/sur_myevic#20]
Hello,
thought that could be useful.
You could implement an autoadjust ohm on locked resistance when certain parameters (as box temperature or anything else) are on a certain level like DNA does. 
I know that it will not be that precise, but still I think that would be nice. :)

**Comment by MicroSur** [comment]
Hello, thanks
I do not know dna and I hate auto-adjust of anything that I locked manually )

**Comment by Dil3mm4** [comment]
Cool, thanks for the reply.
