### ISSUE TITLE
Italian vaping world needs help

### ISSUE THREAD

**Issue by Dil3mm4** [MicroSur/sur_myevic#21]
Sorry to bother you Microsur, and I know that it's not the right place, but Italian vaping world it's in need of help. 

Our governement it's trying to kill the vaping world adding extra taxes on e-liquids (0,39€ per ml) on vaping devices and avoiding Italian resellers to sell all this equipment online. 
The worst thing it's that private users will not be able to buy things on-line from external sources (like gearbest and others) but only from governement smoke shop. 
They're putting their dirty hands on vaping monopolizing it and destroying free marketing opportunities.

We're in need of help, from everybody around the world.

We've started a campagin on change.org at this [link](https://www.change.org/p/pietro-grasso-no-all-emendamento-vicari-che-vede-nicotina-e-sigarette-elettroniche-sotto-monopolio), please if you can, share it on Russian e-cig related forums, every sign could be critical for us.

Thanks for your attention.

**Comment by MicroSur** [comment]
We all on your side. With the same problems.
