### ISSUE TITLE
Code documentation

### ISSUE THREAD

**Issue by Dil3mm4** [MicroSur/sur_myevic#29]
Hello microsur, 

Would you like to documentate the code when you have some free time? 

It would be very nice to understand it better.

Thanks.

**Comment by MicroSur** [comment]
What do U mean?

**Comment by Dil3mm4** [comment]
I mean documentation  for the "whole" source, explaining what routines does, where are located, etc. :)

**Comment by MicroSur** [comment]
I can what I can.
