### ISSUE TITLE
FONT

### ISSUE THREAD

**Issue by Gabriele1992** [MicroSur/sur_myevic#31]
Hello, 
i've upgraded from 3.37 to 5.57 and it isn't the set for the font. 
Like the not bold font. 
if it's possible can u fix it ?

**Box Model:**RX 2/3

**Coil setup:**TFV8 CLOUD BEAST (V8 Q4)

**Comment by MicroSur** [comment]
An additional font in the firmware takes up a lot of space. 
You can create any font package with the help of the VTCFont editor.
