### ISSUE TITLE
А может.....

### ISSUE THREAD

**Issue by falconettt** [MicroSur/sur_myevic#32]
Приветствую, о великий MicroSur!
Давно не заглядывал на гитхаб, ибо доволен был майевиком и не желал ничего более. Но вот оно счастье, ты продолжаешь развивать проект, смотрю появились новые улучшения и дополнения......................варивольт есть, вау! 

У меня просьба нижайшая, бью челом:
1. Можно ли сделать так, чтобы отсечка времени затяжки не сообщала о ее срабатывании?
2. Может позаботишься о геноводах? Там необходимо постоянное маниакальное слежение за сопротивлением. Резкое его падение говорит о КЗ. Как вариант, какое-то визуальное предупреждение о том, что изменение сопротивления на (Х)% имело место?
3. Возможность одновременно видеть" vaped" и "vaped/day" в 3-й и 4-й строке.
4. Автоматический ресет "vaped/day" в 24-00.
5. А как бы зафиксировать затяжку в джоулях? Вот, допустим, знаю я, что при 6-м никотине 60 джоулей на затяг меня устраивает. Тогда при 10 ваттах рассчетное время затяжки - 6 секунд. Но вздумалось мне мощу поднять до 12 ватт, а время затяжки взяло да и до 5 секунд опустилось. Поставил 8 ватт - и тогда 7.5 секунд......

С уважением,

**Comment by MicroSur** [comment]
Привет.
1. Чем то мешает? Это как бы безопасность...
2. Иметь вывод минимального сопротивления в процессе затяжки в инфо строке?
3. Хотелось, но было лениво, пока никто не попросит, сделаю.
4. Ну вроде он так и должен работать ) А когда происходит ресет я никогда и не задумывался глянуть...
5. Мудрёно как то... Протекшен не по секундам, а по джоулям что ли... Можно наверно.

**Comment by falconettt** [comment]
Приветствую.
1. Дык, я на безопасность не посягаю, это святое -). Вопрос только зачем сообщать о срабатывании отсечки и гасить экран? Или, как вариант, иметь возможность настроить с сообщением или без него.
Насколько я помню, этот вопрос обсуждался, clockselect отключил сообщение об отсечке и реализовал защиту каким-то другим способом. В любом случае, иметь возможность настроить длинну затяжки важно, особенно в контексте П.5-го, только сейчас в ручную, приходится примерно высчитывать самому.

2. Не, не во время затяжки. На сетке есть "плавающие" КЗ. Они то возникают, то исчезают. К концу времени службы намотки они появляются все чаще и чаще. На новом и хорошо настроенном быть не должно, ну разве колебания вниз на 1-у 2-е сотых. Как вариант - какой-то счетчик, который показывает, что таких случаев стало много и часто, а значит пора что-то предпринять.

3. Отлично!

4. Оно конечно, и так работает. Но в текущие сутки учитывает показания за все предыдущие до предыдущего ресета, что не совсем корректно. Приходится сбрасывать в ручную каждый день в конце дня. А ресет там сам не происходит, в конечном итоге счетчик показывает нечто среднее за период, длинну которого ты уже и сам забыл.

5. У тебя там MAX раздел есть в меню. Вот бы туда эту функцию вставить.....
Я бы тогда для 6-го никотина выставил бы 60 джоулей.
Для 9-12 никотина где-то 30-40 джоулей.
А для 18-го никотина 20-25 джоулей.
Да и вообще, тогда можно любую крепкость парить без опасности передоза.

**Comment by MicroSur** [comment]
1. Ах вот оно что, я то думаю, почему не работал экран отсечки. Дело в том, что для безопасности нажатия кнопки в кармане, для экрана отсечки есть таймаут (таймаут принадлежит конкретному экрану) для выключения мода вообще. Мне так было проще.
Пока не понимаю, чем плох этот экран. Ну сделайте отсечку больше. Я например тяну столько, сколько комфортно, а не под указку времени отсечки парения ) Это время только для безопасности.
2. Мудрено. Я уже сделал строку в инфо, с отображением минимального сопротивления. Для набора статистики в прошивке просто нет места. А поглядывая на минимальное сопротивление можно сделать вывод, что с койлом что то не так.
3. Не делал пока .bin, но _dec.bin выложен новый, по коммитам же видно.
4. Пробую разобраться с этим выпаренным. Кто бы объяснил, почему после сброса счетчиков и первом пыхе показывает выпаренное например 0.02, а выпаренное в день 0.04
Период сброса выпаренного в день то известен - сутки )
Со автосбросом по времени тоже проблема, у меня есть авто-сброс счетчиков при замене аккума... То есть нужно отделять мух от котлет, делать еще счетчик..
5. Передоз уже регулируется числом пыхов. Регулировать его длиной пыха - это имхо перебор )

**Comment by MicroSur** [comment]
По части выпаренного за день точно буду переделывать. Пусть будет второй счетчик, главное найти, где его обнулять, если полночь и мод спит, пока сопротивляется )

**Comment by falconettt** [comment]
1. И не знаю, какие слова убедительные то подобрать, но для меня этот пункт очень, очень важен....-)))) Ну...прям настаиваю и топаю ножками....-)))

2. Да, нашел минимальное сопротивление.  Пока с ним так попробую. Вопрос закрываем.

3. Да, в  _dec.bin работает. Ну воооот! Уже информативнее.....Вопрос закрываем.

4. Кто бы объяснил - объясняю: рассчетное время скорости всегда с 00-00 дня сброса. Поэтому, если ты сбросил (например) в 1-00 и сделал пару тяг, то счетчик считает что ты куришь со скоростью пару тяг в час, а совпадут показания только в в самом конце, в 24-00. Собсно, в этом и смысл этого счетчика - видишь цифру меньше желаемой  - париришь, цифра больше - не паришь. И так, постепенно, к 24-00 ты приходишь к желаемому объему выпаренного за сутки с минимальной нагрузкой на силу воли.
Проблема (на мой взгляд) сейчас такая - для корректной работы счетчика ты должен дождаться 24-00 и сбросить его в ручную. А если я, например, забыл? А если вообще хочу спать лечь в 22-00?
По инструкции clockselect - встань сутра, сбрось счетчик, и пользуйся им до конца дня. Ну а если у меня день 2 ночи заканчивается, тогда что?
Собсно, поэтому и предлагаю - пусть счетчик обнуляется автоматически в 24-00, другого решения не вижу.

5. У меня ограничения по числу пыхов не дали результата. Даже сказал бы, что результат отрицательный. Через пару месяцев все закончилось повышенной мощностью и увеличенной длиной затяжки. А расход при этом по сути тот же. Типа снижал-снижал и ничего не наснижал. Собсно, именно поэтому возникла идея считать расход жижи.
Настаивать не буду, этот вопрос тоже можно закрыть.

**Comment by MicroSur** [comment]
В бранче аlarm (не в мастере) тестируется _dec.bin со сбросом в полночь, дополнительно галочка в Miscs для сброса и пуффов тоже.

**Comment by falconettt** [comment]
Поставил эту версию. Время 0-34. Сбросил все счетчики в ноль. Похоже скорость не корректно считает (или теперь по другому?), насчитывает практически вровень со счетчиком расхода. Раньше скорость быстро росла после сброса....

**Comment by MicroSur** [comment]
Кто сбросил в ноль, ты или мод?
Да, теперь скорость одинаковая, чтобы этих выкрутасов не было непонятных, только выпаренное за день обнуляется в полночь.

**Comment by falconettt** [comment]
Я сбросил.
Пробую еще раз.
Изменил време так, чтобы 00-00 наступило через два часа. Обнулил счетчики вручную.
Датчик скорости считает точно вровень с датчиком расхода. (??????)
Ровно в полночь датчик скорости обнулился, датчик расхода НЕ обнулился (а должен).
Чего-то не так........

То что было раньше - не выкрутасы. Датчик скорости обладал "предсказательной" способностью. Ну, то есть, датчик скорости показывал то, что покажет датчик расхода в 24-00, если будешь продолжать парить в том же количестве. )Соответственно, если паришь реже и меньше, то показания датчика скорости снижаются.  Если начинаешь много и часто паровозить - показания скорости растут. И в конце периода измерения (24-00) число скорости и число расхода совпадают.
(Имхо) алгоритм работы датчика скорости менять не надо, просто сбросить в нули оба датчика в 24-00 и все.....

**Comment by MicroSur** [comment]
Нету больше скорости. Она вне моего понимания была. Тупо расход и сброс одного счетчика в полночь.
Простити, если убил какую то фичу. Но ее бывшая работа не совместима со сбросом в полночь.

**Comment by falconettt** [comment]
Зачем фичу убивать? Нинада-)).
Лучше уж оставить как было......

А по пункту №1 (экран отсечки убрать) мы сможем найти взаимопонимание?

**Comment by MicroSur** [comment]
Не понимаю я нужность этой скорости вейпа, поэтому будет просто счетчик. Чего там предугадывать надо, какой практический смысл я не знаю.

А по пункту адын ты не убедил, что это как то чему то мешает, топать ножками не вариант )
Ну есть экран отсечки, глянул, почему парение прекратилось - ага, защита, да и парь себе дальше.
