### ISSUE TITLE
Auto change profile and curved preheat

### ISSUE THREAD

**Issue by mrrbt23** [MicroSur/sur_myevic#36]
1. in smart mode the power changes well when i am changing the coil, i've read about that is also changing wattage in power mode when i switch between atomizers if the resistence is saved. It's not doing, maybe i misunderstod something or it is not impemented. It would be great if the profile would change to the right one like in smart mode
2. Curved mode is only adjustable from second 0.5 up 0.0 to 0.4 it is not adjustable.

Box Model: Wismec Reulaux RX GEN3

**Comment by MicroSur** [comment]
There is no Smart capability in Power mode in SME. Choose Profiles manually.

I do not see any problems with setting curves on the entire range. Try to make a reset by long-pressing the Reset first.

**Comment by mrrbt23** [comment]
Okay thanks

**Comment by MicroSur** [comment]
Auto change profile exists now. Menu/Coils/Smart.
