### ISSUE TITLE
Flipscreen bugs

### ISSUE THREAD

**Issue by Dil3mm4** [MicroSur/sur_myevic#5]
**Box Model:**
eVic VTC DUAL
**Steps to reproduce the bug:**
Fire, wait the box raising to the desidered wattage, rapid fire again, the box gets stucked in flipped screen even on standby conditions.

To revert repat again the same combination. 

Guess it has something to do with the update delay on pressing and un-pressing the fire button.

**Comment by MicroSur** [comment]
I never use Fire in this manner )
https://github.com/MicroSur/sur_myevic/commit/455bdf8ede98dc2c236381e4002d3d7f3efaf1f0

**Comment by Dil3mm4** [comment]
A misclick could happen :)
