### ISSUE TITLE
Invert screen problem

### ISSUE THREAD

**Issue by Dil3mm4** [MicroSur/sur_myevic#6]
**Box Model:**
eVic VTC Dual
**Steps to reproduce:**
Turn on Invert on Screen Menu. 
Wait the screen to dim. 
The device stays on white background.

**Comment by MicroSur** [comment]
Inverting occurs immediately, I do not see the problem yet.

**Comment by Dil3mm4** [comment]
I know that occurs immediately, but if you wait for dimming, instead of sleeping, the display stays white.

**Comment by MicroSur** [comment]
It stays white because it is on and inverted )

**Comment by Dil3mm4** [comment]
Dunno it was by design :) Thank you
