### ISSUE TITLE
Coil reading issue

### ISSUE THREAD

**Issue by Dil3mm4** [MicroSur/sur_myevic#7]
**Box Model:**
eVic VTC Dual
**Coil setup:**
Dual coil kanthal a1 28ga 0,50

The firmware in standby displays 0,71, when firing 0.50. 
This doesn't let set to higher wattage.

**Comment by lojpek** [comment]
Clear coils. Coil read wasn't good. U can unscrew your tank when coils are cool and screw again to good read. U can do a 3rd line ohm reader to see property coil ohm.

**Comment by Dil3mm4** [comment]
The live reading says 0.5 the non-live says 0.71
The coils are clear.
Maybe it can be solved with a minor delay on polling for resistance value.

**Comment by MicroSur** [comment]
My kanthal goes from 0.75 to 0.72, dont think this is FW issue...

**Comment by Dil3mm4** [comment]
Why then there's a fluctuation of 0.20? 
Even live resistance says 0.20, the static one 0.70 :(

**Comment by lojpek** [comment]
Your coil read value in non live is wrong written. See if your coil read in menu isn't  blocked. Unscrew tank, reset coils in menu and screw again your tank. Probably you do new setup on tank with box and value of old coil is written in box.

**Comment by Dil3mm4** [comment]
It's not blocked.
There's no use for me to lock it in wattage mode.
Resetting coils doesn't fix it.
And I'm still using the same profile since the flashing of my device.
Even after unscrewing and rescrewing the situation doesn't change.
Static reading states 0.70 on fire 0.50



Il dom 23 lug 2017 21:41 lojpek <notifications@github.com> ha scritto:

**Comment by Dil3mm4** [comment]
The wattage setup relies on static resistance value isn't it?

A solution would be to make it depend on live resistance value.

Il dom 23 lug 2017 21:51 Francesco M. <francoismanzo@gmail.com> ha scritto:

**Comment by lojpek** [comment]
Not really, because if u use Titan or ss your live resistance will be not real resistance after couple of fires. You have some problem with yours setup. If you have no locked resistance in menu then i think that maybe you tank resistant is not good or your coil screws are not good. Try reset values again without tank on box, check your lock status in menu coil manage, put out battery from box then put battery again into the box, install tank and check if something will change.

**Comment by Dil3mm4** [comment]
I'm using kanthal, there's no lock option for that.

"Not really, because if u use Titan or ss your live resistance will be not
real resistance after couple of fires."
True, but still, we're talking about kanthal and only VW mode.

The fluctuation it's totally random, my tank it's just fine and my coils
too, used it on stock and I don't have those probs.

2017-07-23 23:16 GMT+02:00 lojpek <notifications@github.com>:

**Comment by lojpek** [comment]
I'm not using kanthal, only stainless steel mesh200 on avocado24 for like half a year and on the all softwares I have no problem with coil reading, so I thinks that the problem is on your tank side or settings. Regards

**Comment by MicroSur** [comment]
Many changes was maid since issue in FW.
