### ISSUE TITLE
 Difference between myevic and myevic_dec

### ISSUE THREAD

**Issue by Stofkri** [MicroSur/sur_myevic#9]
Hello,
I would like to know the differences between "myevic.bin" and "myevic_dec.bin" please.

**Comment by MicroSur** [comment]
myevic.bin is encoded with joyetech algorithm and ready to flash by any updater.
dec - decoded binary file. Can be used for reverce ingeneering and also can be flashed to the mod with my FWUpdater.

**Comment by Stofkri** [comment]
ok, thanks

**Comment by CGoody564** [comment]
Is this MyEvic bin the same bin file used in the clockselect MyEvic version, or has it been modified in some way?  Want to make sure I save this separately if it is a different bin file

**Comment by MicroSur** [comment]
https://github.com/CGoody564 
These files are different, you can save myevic.bin from this fork as sme.bin

**Comment by CGoody564** [comment]
Thank you for the clarification.  I appreciate it very much.  You just
saved me from my own idiocy
